version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./work:/home/jovyan/work
      - ./ssl-certs:/etc/ssl/notebook
    ports:
      - 8888:8888
    command: "start-notebook.sh \
      --NotebookApp.password=${ACCESS_TOKEN} \
      --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"
